# Generated by Django 6.0.6 on 2026-06-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('poste', models.CharField(max_length=50)),
                ('equipe', models.CharField(max_length=100)),
                ('buts', models.IntegerField(default=0)),
                ('passes', models.IntegerField(default=0)),
                ('cartons_jaunes', models.IntegerField(default=0)),
                ('cartons_rouges', models.IntegerField(default=0)),
                ('minutes_jouees', models.IntegerField(default=0)),
                ('photo', models.URLField(blank=True)),
            ],
        ),
    ]
